apiVersion: apps/v1
kind: Deployment
metadata:
    name: sirona-backend-deployment
    labels:
        app: sirona-backend-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: sirona-backend-deployment
    template:
        metadata:
            labels:
                app: sirona-backend-deployment
        spec:
            containers:
                - name: sirona-backend-deployment
                  image: registry.digitalocean.com/sirona/backend:backend
                  ports:
                      - containerPort: 8080
                  env:
                      - name: OPENAI_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: sirona-backend-secrets
                                key: OPENAI_API_KEY
                      - name: SECRET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: sirona-backend-secrets
                                key: SECRET_KEY
                      - name: SQLALCHEMY_DATABASE_URI
                        valueFrom:
                            secretKeyRef:
                                name: sirona-backend-secrets
                                key: SQLALCHEMY_DATABASE_URI
                      - name: MAILGUN_DOMAIN
                        valueFrom:
                            secretKeyRef:
                                name: sirona-backend-secrets
                                key: MAILGUN_DOMAIN
                      - name: MAILGUN_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: sirona-backend-secrets
                                key: MAILGUN_API_KEY
                      - name: MAILGUN_DEFAULT_SENDER
                        valueFrom:
                            secretKeyRef:
                                name: sirona-backend-secrets
                                key: MAILGUN_DEFAULT_SENDER
                      - name: FRONTEND_URL
                        valueFrom:
                            secretKeyRef:
                                name: sirona-backend-secrets
                                key: FRONTEND_URL
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "500m"
                      limits:
                          memory: "512Mi"
                          cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
    name: pyservice
spec:
    selector:
        app: sirona-backend-deployment
    ports:
        - port: 8000
          targetPort: 8000
    type: LoadBalancer
