name: Build and Push Docker Image

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            # Checkout the code from the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Docker Buildx for advanced build capabilities
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            # Log in to DigitalOcean Container Registry using secrets for authentication
            - name: Log in to DigitalOcean Container Registry
              uses: docker/login-action@v2
              with:
                  registry: registry.digitalocean.com
                  username: ${{ secrets.DOCR_USERNAME }}
                  password: ${{ secrets.DOCR_ACCESS_TOKEN }}

            # Extract metadata such as tags and labels for the Docker image
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      registry.digitalocean.com/${{ secrets.DOCR_REPOSITORY }}/backend

            # Build and push the Docker image to the DigitalOcean Container Registry
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            # Log out from the DigitalOcean Container Registry to clean up
            - name: Log out from DigitalOcean Container Registry
              run: docker logout registry.digitalocean.com
